name: Lint Commit Messages
on: [ push, pull_request ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@latest
        with:
          failOnWarnings: true

