name: Pull Request Labeler

on:
  pull_request_target:
    branches: [ master, develop, release/** ]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        name: Label based on paths
        with:
          sync-labels: true
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: TimonVS/pr-labeler-action@v3
        name: Label based on head branch name
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

